### ISSUE TITLE
Some GLIBC issues with the new version

### ISSUE THREAD

**Issue by iam-Justin** [danacr/drone-cloudflared#1]
> ./cloudflared: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./cloudflared)

I'm using openSUSE Leap 15.1 aarch64.
The highest stable version 2.26 is already installed.  Upgrade Factory version will damage something.
So, is there any other workaround?

**Comment by danacr** [comment]
Can you check which is the latest working version?

**Comment by iam-Justin** [comment]
the latest working version is 0.17.0 / 2019.11.0 .

**Comment by danacr** [comment]
I managed to reproduce the error in my ubuntu aarch64 setup. The problem was with the go docker image. I replaced it with `golang:1.12.9-stretch` for now.  Reference link for the fix: https://github.com/docker-library/golang/issues/298

Fixed starting from [v0.25.0](https://github.com/danacr/drone-cloudflared/releases/tag/0.25.0)

**Comment by iam-Justin** [comment]
Nice~
